project_id = "hetemmltaoirimmoxzku"

[functions.chat-assistant]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.prerender]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false