// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-pages.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-pages.ts
var list_pages_default = defineTool({
  name: "list_pages",
  title: "List pages",
  description: "List content pages (articles and system pages) with slug, status, category and available languages.",
  inputSchema: {
    status: z.enum(["all", "published", "draft"]).optional().describe("Filter by page status. Defaults to 'all'."),
    limit: z.number().int().min(1).max(200).optional().describe("Maximum number of pages to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("pages").select(
      "slug, status, category, is_system_page, is_featured, updated_at, translations:page_translations(language, title)"
    ).order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (status && status !== "all") query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const pages = (data ?? []).map((p) => ({
      slug: p.slug,
      status: p.status,
      category: p.category,
      is_system_page: p.is_system_page,
      is_featured: p.is_featured,
      updated_at: p.updated_at,
      languages: (p.translations ?? []).map((t) => t.language),
      title: p.translations?.[0]?.title ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(pages, null, 2) }],
      structuredContent: { pages }
    };
  }
});

// src/lib/mcp/tools/get-page.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_page_default = defineTool2({
  name: "get_page",
  title: "Get page",
  description: "Get one page by its canonical (English) slug, including every translation with title, meta description, content and JSON-LD schema.",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("The canonical/English page slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("pages").select("*, translations:page_translations(*)").eq("slug", slug).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `Page not found: ${slug}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { page: data }
    };
  }
});

// src/lib/mcp/tools/search-content.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var search_content_default = defineTool3({
  name: "search_content",
  title: "Search content",
  description: "Full-text-ish search across page translations (title, meta description and body) for a keyword, optionally scoped to one language.",
  inputSchema: {
    query: z3.string().trim().min(2).describe("Keyword or phrase to look for."),
    language: z3.string().trim().optional().describe("Optional language filter: 'en', 'br' or 'es'."),
    limit: z3.number().int().min(1).max(50).optional().describe("Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, language, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const escaped = query.replace(/[%,]/g, " ").trim();
    let q = supabase.from("page_translations").select("language, slug, title, meta_description, page_id, pages(slug, status)").or(
      `title.ilike.%${escaped}%,meta_description.ilike.%${escaped}%,content.ilike.%${escaped}%`
    ).limit(limit ?? 10);
    if (language) q = q.eq("language", language);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const results = (data ?? []).map((r) => ({
      language: r.language,
      localized_slug: r.slug,
      canonical_slug: r.pages?.slug ?? null,
      status: r.pages?.status ?? null,
      title: r.title,
      meta_description: r.meta_description
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/upsert-page.ts
import { defineTool as defineTool4, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var translationSchema = z4.object({
  language: z4.string().trim().min(2).describe("Language code: 'en', 'br' or 'es'."),
  title: z4.string().trim().min(1),
  meta_description: z4.string().trim().optional(),
  content: z4.string().optional().describe("HTML content body."),
  localized_slug: z4.string().trim().optional().describe("Localized URL slug."),
  featured_image_alt: z4.string().trim().optional()
});
var upsert_page_default = defineTool4({
  name: "upsert_page",
  title: "Create or update page",
  description: "Create or update a content page and its translations. Defaults to status 'draft'. Requires an admin account; system pages are protected unless force_system_page is true.",
  inputSchema: {
    slug: z4.string().trim().min(1).describe("Canonical (English) URL slug."),
    category: z4.string().trim().optional(),
    status: z4.enum(["draft", "published"]).optional().describe("Defaults to 'draft'."),
    featured_image: z4.string().trim().optional().describe("Full https:// URL to the featured image."),
    author_name: z4.string().trim().optional(),
    read_time: z4.string().trim().optional(),
    tags: z4.array(z4.string()).optional(),
    is_featured: z4.boolean().optional(),
    force_system_page: z4.boolean().optional().describe("Set true to allow overwriting a system page."),
    translations: z4.array(translationSchema).min(1).describe("At least one translation (EN recommended).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    if (input.featured_image && !/^https?:\/\//.test(input.featured_image)) {
      throw new ToolError(
        `featured_image must be a full https:// URL (got "${input.featured_image}").`
      );
    }
    const { data: existing, error: fetchError } = await supabase.from("pages").select("id, is_system_page").eq("slug", input.slug).maybeSingle();
    if (fetchError) {
      return { content: [{ type: "text", text: fetchError.message }], isError: true };
    }
    if (existing?.is_system_page && !input.force_system_page) {
      throw new ToolError(
        `'${input.slug}' is a system page. Set force_system_page: true to overwrite.`
      );
    }
    const pageData = {
      category: input.category ?? null,
      status: input.status ?? "draft",
      featured_image: input.featured_image ?? null,
      author_name: input.author_name ?? null,
      read_time: input.read_time ?? null,
      tags: input.tags ?? [],
      is_featured: input.is_featured ?? false,
      updated_at: (/* @__PURE__ */ new Date()).toISOString()
    };
    let pageId;
    if (existing) {
      const { error } = await supabase.from("pages").update(pageData).eq("id", existing.id);
      if (error) {
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      pageId = existing.id;
      const { error: delErr } = await supabase.from("page_translations").delete().eq("page_id", pageId);
      if (delErr) {
        return { content: [{ type: "text", text: delErr.message }], isError: true };
      }
    } else {
      const { data: created, error } = await supabase.from("pages").insert({ slug: input.slug, ...pageData }).select("id").single();
      if (error) {
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      pageId = created.id;
    }
    const rows = input.translations.map((t) => ({
      page_id: pageId,
      language: t.language,
      title: t.title,
      meta_description: t.meta_description ?? null,
      content: t.content ?? null,
      slug: t.localized_slug ?? input.slug,
      featured_image_alt: t.featured_image_alt ?? null
    }));
    const { error: transErr } = await supabase.from("page_translations").insert(rows);
    if (transErr) {
      return { content: [{ type: "text", text: transErr.message }], isError: true };
    }
    const result = {
      success: true,
      action: existing ? "updated" : "created",
      page_id: pageId,
      slug: input.slug,
      status: pageData.status,
      translations_count: rows.length
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hetemmltaoirimmoxzku";
var mcp_default = defineMcp({
  name: "mangabeira",
  title: "mangabeira",
  version: "0.1.0",
  instructions: "Content tools for mangabeira.net. Use `list_pages` and `search_content` to find articles and system pages, `get_page` to read one page with all its translations (en/br/es), and `upsert_page` to create or update a page (drafts by default). Callers act as their own signed-in account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_pages_default, get_page_default, search_content_default, upsert_page_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
